"""nutrition

Revision ID: 008195d7c1da
Revises: 3c44d4cf83ab
Create Date: 2026-04-01 11:17:57.179368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008195d7c1da'
down_revision = '3c44d4cf83ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('bmi_category', sa.Text(), nullable=True),
    sa.Column('exercise_schedule', sa.Text(), nullable=True),
    sa.Column('meal_plan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_recommendations')
    # ### end Alembic commands ###
