"""initial

Revision ID: 3c44d4cf83ab
Revises: 
Create Date: 2026-03-29 11:49:00.864537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c44d4cf83ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('pre_submitted', sa.Boolean(), nullable=True),
    sa.Column('pre_workout_type', sa.Text(), nullable=True),
    sa.Column('pre_energy_level', sa.Integer(), nullable=True),
    sa.Column('pre_sleep_hours', sa.Integer(), nullable=True),
    sa.Column('pre_water_intake', sa.Integer(), nullable=True),
    sa.Column('pre_mood', sa.Text(), nullable=True),
    sa.Column('pre_injuries', sa.Text(), nullable=True),
    sa.Column('pre_time', sa.Text(), nullable=True),
    sa.Column('post_submitted', sa.Boolean(), nullable=True),
    sa.Column('post_duration', sa.Integer(), nullable=True),
    sa.Column('post_calories', sa.Integer(), nullable=True),
    sa.Column('post_rating', sa.Integer(), nullable=True),
    sa.Column('post_fatigue', sa.Integer(), nullable=True),
    sa.Column('post_completion', sa.Text(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('llm_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid', 'log_date', name='uq_user_date')
    )
    op.create_table('persondetails',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('goal_weight', sa.Integer(), nullable=True),
    sa.Column('going_to_gym', sa.Text(), nullable=True),
    sa.Column('level', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('body_fat', sa.Float(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('dob', sa.Text(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('activity_level', sa.Float(), nullable=True),
    sa.Column('session_len', sa.Text(), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.Column('best_streak', sa.Integer(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('consistency_score', sa.Integer(), nullable=True),
    sa.Column('consistency_feedback', sa.Text(), nullable=True),
    sa.Column('score_updated_date', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('workout_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('exercise_name', sa.String(length=100), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid', 'log_date', 'exercise_name', 'set_index', name='uq_workout_set')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_logs')
    op.drop_table('persondetails')
    op.drop_table('daily_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
